### ISSUE TITLE
bug: Vertical progress bar shifts content of the window in WSL + tmux

### ISSUE THREAD

**Issue by Euromantic** [Im-Beast/deno_tui#12] opened 2022-09-19 21:54 UTC
**Bug description**
Vertical progress bar shifts content of the window in WSL + tmux

**Expected behavior**
Nothing should be shifted

**Reproduction**
Add this to `.zshrc`:
```sh
export TERM=xterm-256color
```
and this to `.tmux.conf`:
```
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"
```

Works fine without tmux. Haven't tested with different tmux and zsh configs.

**Screenshots**
![image](https://user-images.githubusercontent.com/66640708/191126140-b1388bbc-7c4f-4547-9093-45882a8bd5ca.png)

**Information**

- OS: Windows 11 + `Ubuntu 20.04.5` with `Linux 5.10.102.1-microsoft-standard-WSL2 x86_64`
- Deno version:
  ```
  deno 1.25.3 (release, x86_64-unknown-linux-gnu)
  v8 10.6.194.5
  typescript 4.7.4
  ```

**Comment by Im-Beast** [comment] 2022-11-01 12:56
This issue is caused by tmux or WSL (most probably WSL), they improperly render some UNICODE characters and as far as I know I can't do anything about it.

You can set `smooth` property on progress bars to `false` and then spaces will be used for rendering progress, it makes progress less granular and smooth but doesn't cause any issues on WSL.

Keep it mind that when you style progress bars on `smooth: false` you need to set background color instead of foreground one like with `smooth: true`.

Closing for now, if anyone would want to look at it, please do :)

**Closed by Im-Beast** 2022-11-01 12:56 UTC
Labels: bug, wsl
